name: fhir_store
description: A new Flutter project.
version: 0.0.1
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_store

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.2
  cupertino_icons: ^1.0.2
  fhir: ^0.4.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  get: ^4.0.0-nullsafety.2
  google_sign_in: ^5.0.1
  remote_state: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5

flutter:
  uses-material-design: true

        
    
    
                                      