name: mayjuunauthdemo
description: Library to test storing FHIR in Cloud Firestore

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  fhir: ^0.4.0
  fhir_store:
    path: ../../fhir_store
  flutter:
    sdk: flutter
  get: ^4.0.0-nullsafety.2
  remote_state: ^2.0.0


dev_dependencies:
  build_runner: ^1.10.13
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
